apiVersion: batch/v1
kind: Job
metadata:
  name: pod-jobs
  namespace: jobs-cron

spec:
  parallelism: 2              # Specify how many pod replicas a job should run in parallel
  completions: 3              # Specify how many successful pod compleletions are needed to marka job completed
  activeDeadlineSeconds: 40   # Maximum duration the job can run
  backoffLimit: 3             # Specify the number of retry for a job.
  template:                   # Specify the template for the pod which is created by controller
    spec:
      containers:
      - name: my-container
        image: ubuntu
        command: ["echo",  "Salary Plss..."]
      restartPolicy: OnFailure    # Never (Do not restart the job),OnFailure (Restart the job only if it fails),Always (Always restart a job)
