apiVersion: v1
kind: Pod

metadata:
  name: pod-second
  namespace: trainingkube 
  labels:
    name: test
spec:
  containers:
  - name: test
    image: bitbull/webserver
    ports:
    - containerPort: 80       
