apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: trainingkube
data:
  username: QW5pa2V0Cg== 
  password: QW5pa2V0MTEK

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: s-deploy
  namespace: trainingkube
  labels:
    app: testing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testing
  template:
    metadata:
      labels:
        app: testing
    spec:
      containers:
      - name: testing
        image: bitbull/webserver
        ports:
        - containerPort: 80
        env:
        - name: Myusername
          valueFrom:
            secretKeyRef:
              name: secret
              key: username
